---
- name: deploy image
  hosts: staging
  user: deployer
  become: no
  tasks:
    - docker_login:
        registry: docker-registry.techtribe.nl
        username: "{{ CI_BUILD_USER }}"
        password: "{{ CI_BUILD_TOKEN }}"

    - docker_container:
        name: zo-opgelost
        image: "{{ CI_REGISTRY_IMAGE }}"
        pull: true
        state: started
        restart: yes
        restart_policy: always
        restart_retries: 3
        recreate: yes
        env:
          VIRTUAL_HOST: 'zo-opgelost.the-tribes.nl'
          JWT_SECRET: "{{ JWT_SECRET }}"
          JWT_ISSUER: "{{ JWT_ISSUER }}"
          MENDIX_URL: "https://zoopgelost100-accp.mendixcloud.com/rest/"
          MENDIX_USER: "{{ MENDIX_USER }}"
          MENDIX_PASS: "{{ MENDIX_PASS }}"
          MAILGUN_DOMAIN: "{{ MAILGUN_DOMAIN }}"
          MAILGUN_APIKEY: "{{ MAILGUN_APIKEY }}"
          MAILGUN_SENDER: "{{ MAILGUN_SENDER }}"
          SESSION_SECRET: "{{ SESSION_SECRET }}"
...

