---
- name: deploy image
  hosts: staging
  user: deployer
  become: no
  tasks:
    - docker_login:
        registry: docker-registry.techtribe.nl
        username: wessellouwris
        password: vAYEP2gWcd9urxgYZAmW

    - docker_container:
        name: zo-opgelost
        image: "{{ CI_REGISTRY_IMAGE }}"
        pull: true
        state: started
        restart: yes
        restart_policy: always
        restart_retries: 3
        recreate: yes
        env:
          VIRTUAL_HOST: 'zo-opgelost.the-tribes.nl'
...

